{% set name = "jupyter-archive" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cd98691698c5264125aaca4e44e059c0cb75391e9b42e29b353820d2516aecca

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  build:
    - nodejs
  host:
    - python >=3.5
    - pip
    - jupyterlab >=2.0.0
  run:
    - python >=3.5
    - jupyterlab >=2.0.0
    - nodejs
test:
  imports:
    - jupyter_archive
  commands:
    - jupyter labextension list
    - jupyter lab build

about:
  home: https://github.com/hadim/jupyter-archive
  summary: A Jupyter/Jupyterlab extension to make, download and extract archive files.
  description: A Jupyter/Jupyterlab extension to make, download and extract archive files.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
    - fcollonval
